### ISSUE TITLE
complex dictionary

### ISSUE THREAD

**Issue by nemanja-rakicevic** [baalexander/rospy_message_converter#12]
Hi, I have a dictionary that I want to send over ROS which looks like this:
`dictionary = {'left_e0': 0.6745936036696302,
 'left_e1': 1.3535597568240276,
 'left_s0': -1.6707208611310596,
 'left_s1': -1.5144475501651122,
 'left_w0': 0.8013426068418519,
 'left_w1': 0.982298380995793,
 'left_w2': 1.2450093099285662}
`
How should I go about doing this, since applying `message_converter.convert_dictionary_to_ros_message('std_msgs/String', dictionary)` doesn't work?

**Comment by baalexander** [comment]
Hi @nemanja-rakicevic, std_msgs/String takes a dict of the format `{'data': <string>}`. See [this test case](https://github.com/baalexander/rospy_message_converter/blob/master/test/test_message_converter.py#L350-L355) as an example of converting a dict to a std_msgs/String message.
