### ISSUE TITLE
Make this a pip library as well

### ISSUE THREAD

**Issue by cjds** [baalexander/rospy_message_converter#14]
Is it possible to make this a pip library?

**Comment by cjds** [comment]
Yay. I made one. https://pypi.python.org/pypi/rospy_message_converter. If you want to own this, let me know

**Comment by baalexander** [comment]
Hi @cjds, what's the reason for wanting to make rospy_message_converter a PIP library?

**Comment by cjds** [comment]
I just wanted to be able to use it with pyros, as a dependency, instead of through the source code https://pypi.python.org/pypi/pyros/0.2.0

**Comment by asottile** [comment]
To build this with pip I needed the following:

### MANIFEST.in
```
require package.xml
```

(this file should probably be added to this repository)

**Comment by mintar** [comment]
Closing this issue since @cjds already made the pip library himself. :)
