### ISSUE TITLE
Update dict to message function to include service messages?

### ISSUE THREAD

**Issue by jwhendy** [baalexander/rospy_message_converter#16]
Hello,

I'm pretty new to ROS and was going about making some messages and service calls parameter based, but found it clunky. I found I just keep the same lines of code in the node, replacing some `var = value` pair with maybe `var = rospy.get_param('foo')`, or `params = get_param('foo')` and then `var = params['bar'']`. Anyway, I'm sure you get this, as you created this wonderful package!

I was wondering about extending your code to do service calls as well. I took a stab at adding a completely ripped off variant of your `convert_dictionary_to_ros_message()` function and it worked flawlessly! Honestly, other than changing `message` to `service`, there was only one call update to `roslib.message.get_service_class()`.

Thoughts on this?

```
def convert_dictionary_to_ros_service(service_type, dictionary):
    """
    Takes in the service type and a Python dictionary and returns a ROS service request.

    Example:
        service_type = "std_srvs/SetBoolRequest"
        dict_message = { "data": "Hello, Robot" }
        ros_service = convert_dictionary_to_ros_service(service_type, dict_message)
    """
    service_class = roslib.message.get_service_class(service_type)
    service = service_class()
    service_fields = dict(_get_message_fields(service))

    for field_name, field_value in dictionary.items():
        if field_name in service_fields:
            field_type = service_fields[field_name]
            field_value = _convert_to_ros_type(field_type, field_value)
            setattr(service, field_name, field_value)
        else:
            error_message = 'ROS message type "{0}" has no field named "{1}"'\
                .format(service_type, field_name)
            raise ValueError(error_message)

    return service
```

**Comment by mintar** [comment]
Fixed in #17.
