### ISSUE TITLE
No CATKIN_ENABLE_TESTING check

### ISSUE THREAD

**Issue by o-fugi** [baalexander/rospy_message_converter#19]
There should be an if(CATKIN_ENABLE_TESTING) around the add_rostest line in CMakeLists.txt. Otherwise, it throws an error when running catkin_make_isolated: The CMake code should only use it inside a conditional block which checks that testing is enabled.

Fix:

if(CATKIN_ENABLE_TESTING)
add_rostest(...)
endif()

**Comment by mintar** [comment]
Fixed in #9.
