### ISSUE TITLE
message_conversion failes while parsing fixed PointCloud2

### ISSUE THREAD

**Issue by 3shao** [baalexander/rospy_message_converter#20]
Array in message data being read as string, the data of PointCloud2 is interpreted as a random code, not an array. how Can I do?

**Comment by mintar** [comment]
This is not a bug in rospy_message_converter; it's the way the PointCloud2 message is defined. I've successfully used rospy_message_converter to convert PointCloud2 messages from python to ROS message, and never had any problem. If you're looking for a way to parse PointCloud2 messages, please have a look at http://wiki.ros.org/pcl_ros.
