### ISSUE TITLE
Cannot import roslib.message

### ISSUE THREAD

**Issue by pablodo** [baalexander/rospy_message_converter#25]
```
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rospy_message_converter import message_converter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pablo/src/freedomrobotics/freedom_python/env/local/lib/python2.7/site-packages/rospy_message_converter/message_converter.py", line 34, in <module>
    import roslib.message
ImportError: No module named roslib.message
```

I just created a simple virtualenv and installed the library with `pip`.

Is there anyother package that should be installed for running this? It would be nice to add it to the README.

**Comment by mintar** [comment]
You shouldn't install this package via pip. @cjds made the pip library (see #17), but I don't know enough about pip to support it.

If you install this as a normal ROS package, it works. You can either install the binary package (`sudo apt install ros-kinetic-rospy-message-converter`), or build from source inside your catkin workspace.

**Comment by cjds** [comment]
@pablodo I'd recommend closing this issue as it's an issue with my package not the library. You have to install https://pypi.org/project/pyros/0.2.0/ to use this via that pip package. I'll add it as a required dependency and do a pip release. Thanks for letting me know

**Comment by mintar** [comment]
Thanks @cjds for maintaining the pip side of this! :)

**Comment by annesteenbeek** [comment]
@cjds I've installed both pyros and the pip version of the message converter, however it still does not work out of the box. Is there something I'm misisng?
It would be realy nice to be able to use this library without a full ros installation.

**Comment by cjds** [comment]
@annesteenbeek Sorry again for the extremely late reply (not been as on top of notifications as I should have). I am currently working on a re-release of this library that will not have the above traceback. 

It's caused due to a change in requirements from `catkin_pkg` and the fact that I last released this 2 years ago. When I do the update I will let you know
