### ISSUE TITLE
message_conversion failes while parsing fixed size of uint8 array(example : uint8[16] data)

### ISSUE THREAD

**Issue by jihoonl** [baalexander/rospy_message_converter#5]
Hello Brandon,

I wonder if you still maintains this package or not. Recently, I had to patch rosbridge message parser to handle fixed size of uint array like [uuid_msgs.UniqueID](http://docs.ros.org/hydro/api/uuid_msgs/html/msg/UniqueID.html).

So I am just linking the related issue which you might be interested in https://github.com/RobotWebTools/rosbridge_suite/issues/93

**Comment by mintar** [comment]
Fixed by #15.
