### ISSUE TITLE
Parsing PointCloud2 fails

### ISSUE THREAD

**Issue by reinzor** [baalexander/rospy_message_converter#7]
The character array created is of different length than the original byte array.

**Comment by baalexander** [comment]
Thanks @reinzor for bringing this to my attention. Do you have a test that can reproduce this issue?

**Comment by reinzor** [comment]
I will create a simple one tomorrow.

-Rein

**Comment by baalexander** [comment]
Thanks! If you're able to reproduce it as part of rospy_message_converter's [test suite](https://github.com/baalexander/rospy_message_converter/blob/hydro-devel/test/), that's the easiest way for me to verify and to prevent regression issues later.

You can run tests using:

```bash
rostest rospy_message_converter test_all.test
```

**Comment by baalexander** [comment]
This should be resolved now in #15.
